//! Direct comparisons with the archived HHS/ASPR-flumodels R implementation.
//!
//! The committed fixture is generated by `scripts/aspr_reference`. Tests
//! start both implementations from the same explicit E/I state, so this suite
//! does not alter or conceal the production model's all-in-I initialization.

#![cfg(test)]

use crate::mitigations::{
    AntiviralsParams, CommunityMitigationParamsTyped, MitigationParamsTyped, TTIQParams,
    VaccineParams,
};
use crate::model::SEIRModel;
use crate::parameters::ParametersTyped;
use nalgebra::{Matrix2, Vector2};
use serde::Deserialize;
use std::path::PathBuf;

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct Manifest {
    source_repository: String,
    source_revision: String,
    r_version: String,
    #[serde(rename = "deSolve_version")]
    de_solve_version: String,
    aspr_solver_absolute_tolerance: f64,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    manifest: Manifest,
    scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    name: String,
    doses: usize,
    antivirals: bool,
    community: bool,
    days: usize,
    initial_living: Vec<f64>,
    trajectory: Vec<TrajectoryRow>,
    derivative: DerivativeCase,
}

#[derive(Debug, Deserialize)]
struct TrajectoryRow {
    time: f64,
    living: Vec<f64>,
}

#[derive(Debug, Deserialize)]
struct DerivativeCase {
    time: f64,
    living: Vec<f64>,
    expected: Vec<f64>,
}

fn load_fixture() -> Fixture {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/aspr_reference/aspr_reference.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    serde_json::from_str(&raw).expect("ASPR fixture parses")
}

fn parameters(scenario: &Scenario) -> ParametersTyped<2> {
    ParametersTyped {
        population: 1.0,
        population_fractions: Vector2::new(0.4, 0.6),
        population_fraction_labels: Vector2::new("Group 1".into(), "Group 2".into()),
        contact_matrix: Matrix2::new(1.5, 0.2, 0.4, 1.0),
        initial_infections: 0.0,
        fraction_initial_immune: 0.1,
        r0: 1.6,
        latent_period: 2.0,
        infectious_period: 3.0,
        fraction_symptomatic: Vector2::new(0.5, 0.5),
        fraction_hospitalized: Vector2::zeros(),
        hospitalization_delay: 1.0,
        fraction_dead: Vector2::zeros(),
        death_delay: 1.0,
        mitigations: MitigationParamsTyped {
            vaccine: VaccineParams {
                enabled: scenario.doses > 0,
                editable: true,
                doses: scenario.doses.max(1),
                start: 0.0,
                dose2_delay: 7.0,
                p_get_2_doses: 1.0,
                administration_rate: 0.02,
                doses_available: 0.4,
                ramp_up: 5.0,
                ve_s: 0.4,
                ve_i: 0.2,
                ve_p: 0.3,
                ve_2s: 0.7,
                ve_2i: 0.4,
                ve_2p: 0.6,
            },
            antivirals: AntiviralsParams {
                enabled: scenario.antivirals,
                editable: true,
                fraction_adhere: 0.8,
                fraction_diagnosed_prescribed_inpatient: 1.0,
                fraction_diagnosed_prescribed_outpatient: 0.7,
                fraction_seek_care: 0.6,
                ave_i: 0.5,
                ave_p_hosp: 0.0,
                ave_p_death: 0.0,
            },
            community: CommunityMitigationParamsTyped {
                enabled: scenario.community,
                editable: true,
                start: 10.0,
                duration: 15.0,
                effectiveness: Matrix2::new(0.3, 0.1, 0.1, 0.2),
            },
            ttiq: TTIQParams {
                enabled: false,
                editable: true,
                p_id_infectious: 0.0,
                p_infectious_isolates: 0.0,
                isolation_reduction: 0.0,
                p_contact_trace: 0.0,
                p_traced_quarantines: 0.0,
            },
        },
        p_test_sympto: 0.0,
        test_sensitivity: 0.9,
        p_test_forward: 0.9,
    }
}

fn assert_close(actual: f64, expected: f64, abs: f64, rel: f64, context: &str) {
    let tolerance = abs.max(rel * expected.abs());
    assert!(
        (actual - expected).abs() <= tolerance,
        "{context}: actual={actual} expected={expected} tolerance={tolerance}"
    );
}

#[test]
fn reference_derivatives_match_aspr() {
    let fixture = load_fixture();
    assert_eq!(
        fixture.manifest.source_revision,
        "1bee5a596c22a6387a56aa337be5741ca41117a8"
    );
    assert_eq!(fixture.scenarios.len(), 12);
    for scenario in &fixture.scenarios {
        let model = SEIRModel::new(parameters(scenario));
        let actual =
            model.living_derivative_at(scenario.derivative.time, &scenario.derivative.living);
        assert_eq!(actual.len(), scenario.derivative.expected.len());
        for (index, (actual, expected)) in
            actual.iter().zip(&scenario.derivative.expected).enumerate()
        {
            assert_close(
                *actual,
                *expected,
                1e-10,
                1e-8,
                &format!("{} derivative[{index}]", scenario.name),
            );
        }
    }
}

#[test]
fn reference_trajectories_match_aspr() {
    let fixture = load_fixture();
    for scenario in &fixture.scenarios {
        let model = SEIRModel::new(parameters(scenario));
        let actual = model.integrate_living_from_state(scenario.days, &scenario.initial_living);
        assert_eq!(actual.len(), scenario.trajectory.len(), "{}", scenario.name);
        let mut worst_ratio = 0.0_f64;
        let mut worst_context = String::new();
        for ((actual_time, actual_state), expected_row) in actual.iter().zip(&scenario.trajectory) {
            let comparison_end = if scenario.doses > 0 {
                4.0
            } else if scenario.community {
                9.0
            } else {
                scenario.days as f64
            };
            if expected_row.time > comparison_end {
                break;
            }
            assert_close(
                *actual_time,
                expected_row.time,
                1e-12,
                0.0,
                &format!("{} time", scenario.name),
            );
            for (index, (actual, expected)) in
                actual_state.iter().zip(&expected_row.living).enumerate()
            {
                let tolerance = 5e-6_f64.max(1e-5 * expected.abs());
                let ratio = (actual - expected).abs() / tolerance;
                if ratio > worst_ratio {
                    worst_ratio = ratio;
                    worst_context = format!(
                        "{} t={} state[{index}] actual={actual} expected={expected} tolerance={tolerance}",
                        scenario.name, actual_time
                    );
                }
            }
        }
        assert!(worst_ratio <= 1.0, "{worst_context}; ratio={worst_ratio}");
    }
}
