//! Direct comparisons with the archived HHS/ASPR-flumodels R implementation.
//!
//! The committed fixture is generated by `scripts/aspr_reference`. Both
//! implementations are initialized from the same `Parameters`, so they share
//! the same computed initial conditions.

#![cfg(test)]

use crate::model::SEIRModel;
use crate::model_unified::{DynodeModel, OutputType};
use crate::parameters::{Parameters, ParametersTyped};
use serde::Deserialize;
use std::path::PathBuf;

type Fixture = Vec<Simulation>;

#[derive(Debug, Deserialize)]
struct Simulation {
    parameters: Parameters,
    output: Output,
}

#[derive(Debug, Deserialize)]
struct Output {
    total_deaths: Vec<f64>,
    total_hosps: Vec<f64>,
}

fn load_fixture() -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/reference_aspr.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    serde_json::from_str(&raw).expect("ASPR-flumodels fixture parses")
}

fn totals_by_group(
    output: &crate::model_unified::ModelOutput,
    output_type: OutputType,
    n: usize,
) -> Vec<f64> {
    let mut totals = vec![0.0; n];
    for item in output.get_output(&output_type) {
        assert_eq!(
            item.grouped_values.len(),
            n,
            "{output_type:?} output must have {n} subgroups"
        );
        for (total, value) in totals.iter_mut().zip(&item.grouped_values) {
            *total += value;
        }
    }
    totals
}

fn assert_totals_close(actual: &[f64], expected: &[f64], simulation: usize, metric: &str) {
    let abs_tol = 5e-6_f64;
    let rel_tol = 1e-5;
    assert_eq!(
        actual.len(),
        expected.len(),
        "simulation {simulation} {metric}: subgroup count differs"
    );
    for (group, (&actual, &expected)) in actual.iter().zip(expected).enumerate() {
        let tolerance = abs_tol.max(rel_tol * expected.abs());
        assert!(
            (actual - expected).abs() <= tolerance,
            "simulation {simulation} {metric}, group {group}: actual={actual} expected={expected} tolerance={tolerance}"
        );
    }
}

fn check_reference_totals(
    output_type: OutputType,
    expected: impl Fn(&Output) -> &[f64],
    metric: &str,
) {
    let fixture = load_fixture();
    for (simulation_index, simulation) in fixture.iter().enumerate() {
        let n = simulation.parameters.n;
        assert_eq!(n, 2, "fixture must use n=2");
        let expected = expected(&simulation.output);
        assert_eq!(
            expected.len(),
            n,
            "simulation {simulation_index}: {metric} subgroup count"
        );

        let parameters: ParametersTyped<2> =
            ParametersTyped::try_from(simulation.parameters.clone()).expect("parameters parse");
        let model = SEIRModel::new(parameters);
        let output = model.integrate(simulation.parameters.days);
        let actual = totals_by_group(&output, output_type.clone(), n);

        assert_totals_close(&actual, expected, simulation_index, metric);
    }
}

#[test]
fn reference_total_hospitalizations_match_aspr() {
    check_reference_totals(
        OutputType::HospitalIncidence,
        |output| &output.total_hosps,
        "total_hosps",
    );
}

#[test]
fn reference_total_deaths_match_aspr() {
    check_reference_totals(
        OutputType::DeathIncidence,
        |output| &output.total_deaths,
        "total_deaths",
    );
}
